#!/bin/bash

# Define the virtual environment directory and the dependencies file
VENV_DIR="fastAPI"
REQUIREMENTS_FILE="requirements.txt"

# Function to check and install packages if not installed
install_if_not_installed() {
    PACKAGE_NAME=$1
    dpkg -s "$PACKAGE_NAME" &>/dev/null

    if [ $? -ne 0 ]; then
        echo "$PACKAGE_NAME is not installed. Installing..."
        sudo apt-get update
        sudo apt-get install -y "$PACKAGE_NAME"
    else
        echo "$PACKAGE_NAME is already installed."
    fi
}

# Check for Python3 and python3-venv
install_if_not_installed "python3"
install_if_not_installed "python3-venv"

# Check if the virtual environment directory exists
if [ ! -d "$VENV_DIR" ]; then
    echo "Virtual environment not found. Creating one..."
    python3 -m venv "$VENV_DIR"
fi

# Activate the virtual environment
source "$VENV_DIR/bin/activate"

# Upgrade pip
pip install --upgrade pip

# Install necessary packages
if [ -f "$REQUIREMENTS_FILE" ]; then
    echo "Installing dependencies from $REQUIREMENTS_FILE..."
    pip install -r "$REQUIREMENTS_FILE"
else
    echo "$REQUIREMENTS_FILE not found. Installing FastAPI..."
    pip install fastapi
fi

# Run the FastAPI application
fastapi dev app/main.py --reload --host 0.0.0.0 --port 35003
